// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://carvweksypdafdifgriq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhcnZ3ZWtzeXBkYWZkaWZncmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNTU2MDEsImV4cCI6MjA1MDkzMTYwMX0.1CKSGVzQhn2Zq8posesntcj5PQF1lPua3e1HWzqn99c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);